FROM ubuntu:22.04

RUN apt-get update &&  \
    apt-get install -y -q software-properties-common && add-apt-repository -y ppa:mongoose-os/mos && \
    apt -q install -y mos-latest docker.io make git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
