name: build-shelly-homekit
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check formatting
        run: make check-format
      - name: Build docker image # remove if newer mos docker image is available
        run: docker build -t mgos/esp32-build:4.4.1-r7 -f .github/workflows/Dockerfile-esp32-build .
      - name: Install mos build tool
        run: |
          sudo add-apt-repository -y ppa:mongoose-os/mos
          sudo apt -q install -y mos-latest
      - name: Build project
        run: make release RELEASE_SUFFIX=$(.github/version.py --suffix)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: releases
          path: |
            releases/*
            !releases/**/elf
          if-no-files-found: error
